"""cambio_factura_remito

Revision ID: 02a1461788bb
Revises: a1c4e6f0b2d7
Create Date: 2026-08-24 18:37:39.008552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02a1461788bb'
down_revision: Union[str, None] = 'a1c4e6f0b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_customer_payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('online_customer_account_movement_id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['online_customer_account_movement_id'], ['online_customer_account_movements.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_customer_payment_allocations_id'), 'online_customer_payment_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_online_customer_payment_allocations_online_customer_account_movement_id'), 'online_customer_payment_allocations', ['online_customer_account_movement_id'], unique=False)
    op.create_index(op.f('ix_online_customer_payment_allocations_sales_invoice_id'), 'online_customer_payment_allocations', ['sales_invoice_id'], unique=False)
    op.drop_index('ix_sales_invoice_payments_created_by', table_name='sales_invoice_payments')
    op.drop_index('ix_sales_invoice_payments_id', table_name='sales_invoice_payments')
    op.drop_index('ix_sales_invoice_payments_sales_invoice_id', table_name='sales_invoice_payments')
    op.drop_table('sales_invoice_payments')
    op.drop_column('purchase_invoices', 'invoice_type')
    op.drop_column('sales_invoices', 'invoice_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoices', sa.Column('invoice_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('purchase_invoices', sa.Column('invoice_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_table('sales_invoice_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sales_invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sales_reps.id'], name='sales_invoice_payments_created_by_fkey'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], name='sales_invoice_payments_sales_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_invoice_payments_pkey')
    )
    op.create_index('ix_sales_invoice_payments_sales_invoice_id', 'sales_invoice_payments', ['sales_invoice_id'], unique=False)
    op.create_index('ix_sales_invoice_payments_id', 'sales_invoice_payments', ['id'], unique=False)
    op.create_index('ix_sales_invoice_payments_created_by', 'sales_invoice_payments', ['created_by'], unique=False)
    op.drop_index(op.f('ix_online_customer_payment_allocations_sales_invoice_id'), table_name='online_customer_payment_allocations')
    op.drop_index(op.f('ix_online_customer_payment_allocations_online_customer_account_movement_id'), table_name='online_customer_payment_allocations')
    op.drop_index(op.f('ix_online_customer_payment_allocations_id'), table_name='online_customer_payment_allocations')
    op.drop_table('online_customer_payment_allocations')
    # ### end Alembic commands ###
