"""fixes models compra y venta

Revision ID: 0b4431e3f68f
Revises: c4e7a91d2b58
Create Date: 2026-09-24 18:52:55.358174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4431e3f68f'
down_revision: Union[str, None] = 'c4e7a91d2b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_quote_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_quote_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sales_reps.id'], ),
    sa.ForeignKeyConstraint(['sales_quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quote_payments_created_by'), 'sales_quote_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_sales_quote_payments_id'), 'sales_quote_payments', ['id'], unique=False)
    op.create_index(op.f('ix_sales_quote_payments_sales_quote_id'), 'sales_quote_payments', ['sales_quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quote_payments_sales_quote_id'), table_name='sales_quote_payments')
    op.drop_index(op.f('ix_sales_quote_payments_id'), table_name='sales_quote_payments')
    op.drop_index(op.f('ix_sales_quote_payments_created_by'), table_name='sales_quote_payments')
    op.drop_table('sales_quote_payments')
    # ### end Alembic commands ###
