"""add image snapshot

Revision ID: 223f525629df
Revises: 69b68628ce22
Create Date: 2026-06-04 22:26:49.849518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223f525629df'
down_revision: Union[str, None] = '69b68628ce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_clients', sa.Integer(), nullable=False),
    sa.Column('total_products_sold', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('average_ticket', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_analytics_daily_date')
    )
    op.create_index(op.f('ix_analytics_daily_date'), 'analytics_daily', ['date'], unique=False)
    op.create_table('analytics_product_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'product_id', name='uq_analytics_product_daily_date_product')
    )
    op.create_index(op.f('ix_analytics_product_daily_date'), 'analytics_product_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_product_daily_product_id'), 'analytics_product_daily', ['product_id'], unique=False)
    op.create_table('analytics_sales_rep_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_clients', sa.Integer(), nullable=False),
    sa.Column('total_products_sold', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'sales_rep_id', name='uq_analytics_sales_rep_daily_date_rep')
    )
    op.create_index(op.f('ix_analytics_sales_rep_daily_date'), 'analytics_sales_rep_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_sales_rep_daily_sales_rep_id'), 'analytics_sales_rep_daily', ['sales_rep_id'], unique=False)
    op.create_table('analytics_zone_product_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('h3_index', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unique_clients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'h3_index', 'product_id', name='uq_analytics_zone_product_daily')
    )
    op.create_index(op.f('ix_analytics_zone_product_daily_date'), 'analytics_zone_product_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_zone_product_daily_h3_index'), 'analytics_zone_product_daily', ['h3_index'], unique=False)
    op.create_index(op.f('ix_analytics_zone_product_daily_product_id'), 'analytics_zone_product_daily', ['product_id'], unique=False)
    op.add_column('order_items', sa.Column('product_image_url_snapshot', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_image_url_snapshot')
    op.drop_index(op.f('ix_analytics_zone_product_daily_product_id'), table_name='analytics_zone_product_daily')
    op.drop_index(op.f('ix_analytics_zone_product_daily_h3_index'), table_name='analytics_zone_product_daily')
    op.drop_index(op.f('ix_analytics_zone_product_daily_date'), table_name='analytics_zone_product_daily')
    op.drop_table('analytics_zone_product_daily')
    op.drop_index(op.f('ix_analytics_sales_rep_daily_sales_rep_id'), table_name='analytics_sales_rep_daily')
    op.drop_index(op.f('ix_analytics_sales_rep_daily_date'), table_name='analytics_sales_rep_daily')
    op.drop_table('analytics_sales_rep_daily')
    op.drop_index(op.f('ix_analytics_product_daily_product_id'), table_name='analytics_product_daily')
    op.drop_index(op.f('ix_analytics_product_daily_date'), table_name='analytics_product_daily')
    op.drop_table('analytics_product_daily')
    op.drop_index(op.f('ix_analytics_daily_date'), table_name='analytics_daily')
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###
