"""add passwords to client_model

Revision ID: 24f3add0f956
Revises: 39cf238f7e95
Create Date: 2026-09-08 15:53:34.265563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f3add0f956'
down_revision: Union[str, None] = '39cf238f7e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'hashed_password')
    # ### end Alembic commands ###
