"""agregado de supplier snapshot en purchase invoice model

Revision ID: 337a05a558a3
Revises: fdd237c10fe0
Create Date: 2026-06-03 05:25:06.129566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '337a05a558a3'
down_revision: Union[str, None] = 'fdd237c10fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_invoices', sa.Column('supplier_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_invoices', 'supplier_snapshot')
    # ### end Alembic commands ###
