"""add snapshot purchase invoice model

Revision ID: 3536410ec6c4
Revises: 9a99765d6da4
Create Date: 2026-06-03 16:28:12.056475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3536410ec6c4'
down_revision: Union[str, None] = '9a99765d6da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_invoices', sa.Column('supplier_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('purchase_invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_invoices', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('purchase_invoices', 'supplier_snapshot')
    # ### end Alembic commands ###
