"""Cambios models

Revision ID: 37e2e0430b7f
Revises: 45ca087a0cbd
Create Date: 2026-06-01 15:16:30.793867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37e2e0430b7f'
down_revision: Union[str, None] = '45ca087a0cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Definir el objeto ENUM para PostgreSQL de forma explícita
sales_type_enum = postgresql.ENUM('B2B', 'ONLINE', name='sales_type_enum')


def upgrade() -> None:
    # 1. Crear el tipo ENUM en la base de datos antes de usarlo
    sales_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_brand_snapshot', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('product_sku_snapshot', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('sales_type', sa.Enum('B2B', 'ONLINE', name='sales_type_enum'), server_default='ONLINE', nullable=False))
    op.add_column('orders', sa.Column('client_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('client_branch_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('sales_rep_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('preferred_delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('scheduled_delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('invoice_generated', sa.Boolean(), nullable=False))
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_sales_rep_id', table_name='orders')
    op.create_index(op.f('ix_orders_preferred_delivery_date'), 'orders', ['preferred_delivery_date'], unique=False)
    op.create_index('ix_orders_sales_rep_delivery_date', 'orders', ['sales_rep_id', 'scheduled_delivery_date'], unique=False)
    op.create_index(op.f('ix_orders_sales_type'), 'orders', ['sales_type'], unique=False)
    op.create_index(op.f('ix_orders_scheduled_delivery_date'), 'orders', ['scheduled_delivery_date'], unique=False)
    op.create_index('ix_orders_scheduled_delivery_status', 'orders', ['scheduled_delivery_date', 'status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_column('orders', 'order_type')
    op.create_unique_constraint('uq_purchase_invoice_number_supplier', 'purchase_invoices', ['invoice_number', 'supplier_id'])
    op.add_column('sales_invoice_items', sa.Column('product_name', sa.String(length=255), nullable=False))
    op.add_column('sales_invoice_items', sa.Column('product_brand', sa.String(length=255), nullable=True))
    op.add_column('sales_invoice_items', sa.Column('product_sku', sa.String(length=120), nullable=True))
    op.add_column('sales_invoice_items', sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('sales_invoice_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sales_invoices', sa.Column('sales_type', sa.Enum('B2B', 'ONLINE', name='sales_type_enum'), nullable=False))
    op.add_column('sales_invoices', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('sales_invoices', sa.Column('customer_phone', sa.String(length=50), nullable=True))
    op.add_column('sales_invoices', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('sales_invoices', sa.Column('delivery_type', sa.String(length=20), nullable=True))
    op.add_column('sales_invoices', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('sales_invoices', sa.Column('delivery_city', sa.String(length=120), nullable=True))
    op.add_column('sales_invoices', sa.Column('delivery_reference', sa.Text(), nullable=True))
    op.add_column('sales_invoices', sa.Column('client_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_invoices', sa.Column('client_branch_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_invoices', sa.Column('sales_rep_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_invoices', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('sales_invoices', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_invoices', sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_invoices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sales_invoices', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_invoices', 'sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_sales_invoices_customer_email'), 'sales_invoices', ['customer_email'], unique=False)
    op.create_index(op.f('ix_sales_invoices_sales_type'), 'sales_invoices', ['sales_type'], unique=False)
    op.create_unique_constraint('uq_sales_invoice_number', 'sales_invoices', ['invoice_number'])
    op.create_unique_constraint('uq_sales_invoice_order_id', 'sales_invoices', ['order_id'])
    op.add_column('sales_reps', sa.Column('home_lat', sa.Float(), nullable=True))
    op.add_column('sales_reps', sa.Column('home_lng', sa.Float(), nullable=True))
    op.add_column('sales_reps', sa.Column('coverage_radius_km', sa.Float(), nullable=True))
    op.add_column('sales_reps', sa.Column('home_h3_index', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_sales_reps_home_h3_index'), 'sales_reps', ['home_h3_index'], unique=False)
    op.create_index(op.f('ix_sales_reps_name'), 'sales_reps', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_reps_name'), table_name='sales_reps')
    op.drop_index(op.f('ix_sales_reps_home_h3_index'), table_name='sales_reps')
    op.drop_column('sales_reps', 'home_h3_index')
    op.drop_column('sales_reps', 'coverage_radius_km')
    op.drop_column('sales_reps', 'home_lng')
    op.drop_column('sales_reps', 'home_lat')
    op.drop_constraint('uq_sales_invoice_order_id', 'sales_invoices', type_='unique')
    op.drop_constraint('uq_sales_invoice_number', 'sales_invoices', type_='unique')
    op.drop_index(op.f('ix_sales_invoices_sales_type'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_customer_email'), table_name='sales_invoices')
    op.alter_column('sales_invoices', 'sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_invoices', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales_invoices', 'updated_at')
    op.drop_column('sales_invoices', 'email_sent_at')
    op.drop_column('sales_invoices', 'pdf_generated_at')
    op.drop_column('sales_invoices', 'currency')
    op.drop_column('sales_invoices', 'sales_rep_snapshot')
    op.drop_column('sales_invoices', 'client_branch_snapshot')
    op.drop_column('sales_invoices', 'client_snapshot')
    op.drop_column('sales_invoices', 'delivery_reference')
    op.drop_column('sales_invoices', 'delivery_city')
    op.drop_column('sales_invoices', 'delivery_address')
    op.drop_column('sales_invoices', 'delivery_type')
    op.drop_column('sales_invoices', 'customer_email')
    op.drop_column('sales_invoices', 'customer_phone')
    op.drop_column('sales_invoices', 'customer_name')
    op.drop_column('sales_invoices', 'sales_type')
    op.alter_column('sales_invoice_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales_invoice_items', 'product_snapshot')
    op.drop_column('sales_invoice_items', 'product_sku')
    op.drop_column('sales_invoice_items', 'product_brand')
    op.drop_column('sales_invoice_items', 'product_name')
    op.drop_constraint('uq_purchase_invoice_number_supplier', 'purchase_invoices', type_='unique')
    op.add_column('orders', sa.Column('order_type', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_scheduled_delivery_status', table_name='orders')
    op.drop_index(op.f('ix_orders_scheduled_delivery_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_sales_type'), table_name='orders')
    op.drop_index('ix_orders_sales_rep_delivery_date', table_name='orders')
    op.drop_index(op.f('ix_orders_preferred_delivery_date'), table_name='orders')
    op.create_index('ix_orders_sales_rep_id', 'orders', ['sales_rep_id'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.drop_column('orders', 'invoice_generated')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'scheduled_delivery_date')
    op.drop_column('orders', 'preferred_delivery_date')
    op.drop_column('orders', 'sales_rep_snapshot')
    op.drop_column('orders', 'client_branch_snapshot')
    op.drop_column('orders', 'client_snapshot')
    op.drop_column('orders', 'sales_type')
    op.drop_column('order_items', 'product_sku_snapshot')
    op.drop_column('order_items', 'product_brand_snapshot')
    # ### end Alembic commands ###