"""product model fixed

Revision ID: 45ca087a0cbd
Revises: 894e5d7bbaa7
Create Date: 2026-05-07 18:10:09.227080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ca087a0cbd'
down_revision: Union[str, None] = '894e5d7bbaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
