"""add new models online customer and analytics online customer daily

Revision ID: 60cecc3cdbd8
Revises: fb19054d04ad
Create Date: 2026-06-17 04:32:43.122862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60cecc3cdbd8'
down_revision: Union[str, None] = 'fb19054d04ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_normalized', sa.String(length=255), nullable=True),
    sa.Column('phone_normalized', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_customers_email_normalized'), 'online_customers', ['email_normalized'], unique=True)
    op.create_index(op.f('ix_online_customers_id'), 'online_customers', ['id'], unique=False)
    op.create_index(op.f('ix_online_customers_phone_normalized'), 'online_customers', ['phone_normalized'], unique=True)
    op.create_table('analytics_online_customer_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('online_customer_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('products_bought', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('unique_products_count', sa.Integer(), nullable=False),
    sa.Column('categories_summary', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['online_customer_id'], ['online_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'online_customer_id', name='uq_analytics_online_customer_daily_date_customer')
    )
    op.create_index(op.f('ix_analytics_online_customer_daily_date'), 'analytics_online_customer_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_online_customer_daily_online_customer_id'), 'analytics_online_customer_daily', ['online_customer_id'], unique=False)
    op.add_column('sales_invoices', sa.Column('online_customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_invoices_online_customer_id'), 'sales_invoices', ['online_customer_id'], unique=False)
    op.create_foreign_key(None, 'sales_invoices', 'online_customers', ['online_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_sales_invoices_online_customer_id'), table_name='sales_invoices')
    op.drop_column('sales_invoices', 'online_customer_id')
    op.drop_index(op.f('ix_analytics_online_customer_daily_online_customer_id'), table_name='analytics_online_customer_daily')
    op.drop_index(op.f('ix_analytics_online_customer_daily_date'), table_name='analytics_online_customer_daily')
    op.drop_table('analytics_online_customer_daily')
    op.drop_index(op.f('ix_online_customers_phone_normalized'), table_name='online_customers')
    op.drop_index(op.f('ix_online_customers_id'), table_name='online_customers')
    op.drop_index(op.f('ix_online_customers_email_normalized'), table_name='online_customers')
    op.drop_table('online_customers')
    # ### end Alembic commands ###
