"""add analytics and relationships

Revision ID: 69b68628ce22
Revises: 3536410ec6c4
Create Date: 2026-06-03 20:39:45.689860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b68628ce22'
down_revision: Union[str, None] = '3536410ec6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_catalog_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('zone_h3_index', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_event_created_at', 'analytics_catalog_events', ['created_at'], unique=False)
    op.create_index('idx_catalog_event_product_created', 'analytics_catalog_events', ['product_id', 'created_at'], unique=False)
    op.create_index('idx_catalog_event_sales_rep_created', 'analytics_catalog_events', ['sales_rep_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_client_id'), 'analytics_catalog_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_created_at'), 'analytics_catalog_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_event_type'), 'analytics_catalog_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_product_id'), 'analytics_catalog_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_sales_rep_id'), 'analytics_catalog_events', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_session_id'), 'analytics_catalog_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_source'), 'analytics_catalog_events', ['source'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_visitor_id'), 'analytics_catalog_events', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_analytics_catalog_events_zone_h3_index'), 'analytics_catalog_events', ['zone_h3_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_catalog_events_zone_h3_index'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_visitor_id'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_source'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_session_id'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_sales_rep_id'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_product_id'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_event_type'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_created_at'), table_name='analytics_catalog_events')
    op.drop_index(op.f('ix_analytics_catalog_events_client_id'), table_name='analytics_catalog_events')
    op.drop_index('idx_catalog_event_sales_rep_created', table_name='analytics_catalog_events')
    op.drop_index('idx_catalog_event_product_created', table_name='analytics_catalog_events')
    op.drop_index('idx_catalog_event_created_at', table_name='analytics_catalog_events')
    op.drop_table('analytics_catalog_events')
    # ### end Alembic commands ###
