"""fix_quotes

Revision ID: 6f05112e6791
Revises: c4bef0e34d66
Create Date: 2026-09-29 00:28:37.046091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f05112e6791'
down_revision: Union[str, None] = 'c4bef0e34d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_quote_items', 'discount_amount')
    op.drop_column('sales_quote_items', 'discount_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_quote_items', sa.Column('discount_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    op.add_column('purchase_quote_items', sa.Column('discount_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
