"""fix sales_invoice_payment

Revision ID: 798a66242d5a
Revises: 02a1461788bb
Create Date: 2026-08-24 22:36:33.670195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798a66242d5a'
down_revision: Union[str, None] = '02a1461788bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sales_reps.id'], ),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_invoice_payments_created_by'), 'sales_invoice_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_sales_invoice_payments_id'), 'sales_invoice_payments', ['id'], unique=False)
    op.create_index(op.f('ix_sales_invoice_payments_sales_invoice_id'), 'sales_invoice_payments', ['sales_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoice_payments_sales_invoice_id'), table_name='sales_invoice_payments')
    op.drop_index(op.f('ix_sales_invoice_payments_id'), table_name='sales_invoice_payments')
    op.drop_index(op.f('ix_sales_invoice_payments_created_by'), table_name='sales_invoice_payments')
    op.drop_table('sales_invoice_payments')
    # ### end Alembic commands ###
