"""fix relations online_customer_account_movement_model and sales_invoice_model

Revision ID: 79becee851af
Revises: 798a66242d5a
Create Date: 2026-08-27 11:52:55.653069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79becee851af'
down_revision: Union[str, None] = '798a66242d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
