"""product delete barcode field

Revision ID: 894e5d7bbaa7
Revises: 9da9a61170fc
Create Date: 2026-05-07 05:56:12.055569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894e5d7bbaa7'
down_revision: Union[str, None] = '9da9a61170fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    # ### end Alembic commands ###
