"""fix sales quote payment model

Revision ID: 935c3d0b21f9
Revises: 0b4431e3f68f
Create Date: 2026-09-24 20:06:14.077893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935c3d0b21f9'
down_revision: Union[str, None] = '0b4431e3f68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
