"""client branch model fix

Revision ID: 9ba0ba83f70e
Revises: a3649290ef79
Create Date: 2026-05-06 13:54:26.786357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba0ba83f70e'
down_revision: Union[str, None] = 'a3649290ef79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_branches', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('client_branches', 'lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('client_branches', 'lng',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('client_branches', 'lat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    # ### end Alembic commands ###
