"""productconstraint fix

Revision ID: a3c283b64dcf
Revises: ec4dcccb8c4b
Create Date: 2026-05-06 18:03:56.995860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c283b64dcf'
down_revision: Union[str, None] = 'ec4dcccb8c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
