"""fixes

Revision ID: a7ea019535e6
Revises: e3279fcddde6
Create Date: 2026-09-09 17:09:48.674483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ea019535e6'
down_revision: Union[str, None] = 'e3279fcddde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # La migración paralela (b7e2c4a9f1d6) ya eliminó la tabla y las restricciones de online_customer.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoices', sa.Column('online_customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sales_invoices_online_customer_id_fkey', 'sales_invoices', 'online_customers', ['online_customer_id'], ['id'])
    op.create_index('ix_sales_invoices_online_customer_id', 'sales_invoices', ['online_customer_id'], unique=False)
    # ### end Alembic commands ###