"""add presupuesto compra y venta

Revision ID: aa86432a02f3
Revises: 17d3c1df009e
Create Date: 2026-09-23 18:57:56.992037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa86432a02f3'
down_revision: Union[str, None] = '17d3c1df009e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_tax_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quote_number', sa.String(length=100), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'approved', 'rejected', 'expired')", name='ck_purchase_quote_status'),
    sa.ForeignKeyConstraint(['created_by'], ['sales_reps.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number', 'supplier_id', name='uq_purchase_quote_number_supplier')
    )
    op.create_index(op.f('ix_purchase_quotes_created_by'), 'purchase_quotes', ['created_by'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_id'), 'purchase_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_quote_number'), 'purchase_quotes', ['quote_number'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_status'), 'purchase_quotes', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_supplier_id'), 'purchase_quotes', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_supplier_name'), 'purchase_quotes', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_purchase_quotes_supplier_tax_id'), 'purchase_quotes', ['supplier_tax_id'], unique=False)
    op.create_table('purchase_quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_quote_id'], ['purchase_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_quote_items_id'), 'purchase_quote_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_quote_items_product_id'), 'purchase_quote_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_quote_items_purchase_quote_id'), 'purchase_quote_items', ['purchase_quote_id'], unique=False)
    op.create_table('sales_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_tax_id', sa.String(length=50), nullable=True),
    sa.Column('client_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('quote_number', sa.String(length=100), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'approved', 'rejected', 'expired')", name='ck_sales_quote_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number', 'client_id', name='uq_sales_quote_number_client')
    )
    op.create_index(op.f('ix_sales_quotes_client_id'), 'sales_quotes', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_client_name'), 'sales_quotes', ['client_name'], unique=False)
    op.create_index(op.f('ix_sales_quotes_id'), 'sales_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_quote_number'), 'sales_quotes', ['quote_number'], unique=False)
    op.create_index(op.f('ix_sales_quotes_sales_rep_id'), 'sales_quotes', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_status'), 'sales_quotes', ['status'], unique=False)
    op.create_table('sales_quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_quote_id'], ['sales_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quote_items_id'), 'sales_quote_items', ['id'], unique=False)
    op.create_index(op.f('ix_sales_quote_items_product_id'), 'sales_quote_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_items_sales_quote_id'), 'sales_quote_items', ['sales_quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quote_items_sales_quote_id'), table_name='sales_quote_items')
    op.drop_index(op.f('ix_sales_quote_items_product_id'), table_name='sales_quote_items')
    op.drop_index(op.f('ix_sales_quote_items_id'), table_name='sales_quote_items')
    op.drop_table('sales_quote_items')
    op.drop_index(op.f('ix_sales_quotes_status'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_sales_rep_id'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_quote_number'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_id'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_client_name'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_client_id'), table_name='sales_quotes')
    op.drop_table('sales_quotes')
    op.drop_index(op.f('ix_purchase_quote_items_purchase_quote_id'), table_name='purchase_quote_items')
    op.drop_index(op.f('ix_purchase_quote_items_product_id'), table_name='purchase_quote_items')
    op.drop_index(op.f('ix_purchase_quote_items_id'), table_name='purchase_quote_items')
    op.drop_table('purchase_quote_items')
    op.drop_index(op.f('ix_purchase_quotes_supplier_tax_id'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_supplier_name'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_supplier_id'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_status'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_quote_number'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_id'), table_name='purchase_quotes')
    op.drop_index(op.f('ix_purchase_quotes_created_by'), table_name='purchase_quotes')
    op.drop_table('purchase_quotes')
    # ### end Alembic commands ###
