"""fix model order

Revision ID: c58f6398a62d
Revises: 6af2c29c7f92
Create Date: 2026-04-08 13:02:35.392793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58f6398a62d'
down_revision: Union[str, None] = '6af2c29c7f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'delivery_city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
