"""fixes updated

Revision ID: d89fefa1d8fa
Revises: e5c2b7be5965
Create Date: 2026-04-28 07:45:11.097040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89fefa1d8fa'
down_revision: Union[str, None] = 'e5c2b7be5965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('client_branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_client_branch_id'), 'orders', ['client_branch_id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'client_branches', ['client_branch_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_branch_id'), table_name='orders')
    op.drop_column('orders', 'client_branch_id')
    op.drop_column('orders', 'client_id')
    # ### end Alembic commands ###
