"""fixes order model

Revision ID: e12a764fe301
Revises: 7e80df87c23f
Create Date: 2026-05-04 14:54:06.764683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12a764fe301'
down_revision: Union[str, None] = '7e80df87c23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'sales_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
