"""add client daily job and fixes

Revision ID: eb9e4a92937e
Revises: 38dda231e301
Create Date: 2026-06-06 19:42:58.266606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9e4a92937e'
down_revision: Union[str, None] = '38dda231e301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_product_daily', sa.Column('total_orders', sa.Integer(), nullable=False))
    op.add_column('analytics_product_daily', sa.Column('unique_clients', sa.Integer(), nullable=False))
    op.add_column('analytics_zone_product_daily', sa.Column('total_orders', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_zone_product_daily', 'total_orders')
    op.drop_column('analytics_product_daily', 'unique_clients')
    op.drop_column('analytics_product_daily', 'total_orders')
    # ### end Alembic commands ###
