"""fixes relationships

Revision ID: f0057a554619
Revises: eb9e4a92937e
Create Date: 2026-06-06 20:03:01.328151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0057a554619'
down_revision: Union[str, None] = 'eb9e4a92937e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_client_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('products_bought', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('unique_products_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'client_id', name='uq_analytics_client_daily_date_client')
    )
    op.create_index(op.f('ix_analytics_client_daily_client_id'), 'analytics_client_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_analytics_client_daily_date'), 'analytics_client_daily', ['date'], unique=False)
    op.alter_column('sales_invoices', 'margin_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_invoices', 'margin_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_analytics_client_daily_date'), table_name='analytics_client_daily')
    op.drop_index(op.f('ix_analytics_client_daily_client_id'), table_name='analytics_client_daily')
    op.drop_table('analytics_client_daily')
    # ### end Alembic commands ###
