"""cambios fix models

Revision ID: f20d92776349
Revises: 1ad4cc3987fa
Create Date: 2026-06-01 17:33:36.667759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f20d92776349'
down_revision: Union[str, None] = '1ad4cc3987fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_catalog_event_created_at', table_name='analytics_catalog_events')
    op.drop_index('idx_catalog_event_product_created', table_name='analytics_catalog_events')
    op.drop_index('idx_catalog_event_sales_rep_created', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_created_at', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_event_type', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_product_id', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_sales_rep_id', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_session_id', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_source', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_visitor_id', table_name='analytics_catalog_events')
    op.drop_index('ix_analytics_catalog_events_zone_h3_index', table_name='analytics_catalog_events')
    op.drop_table('analytics_catalog_events')
    op.drop_index('idx_analytics_product_daily_date_product', table_name='analytics_product_daily')
    op.drop_index('ix_analytics_product_daily_client_id', table_name='analytics_product_daily')
    op.drop_index('ix_analytics_product_daily_date', table_name='analytics_product_daily')
    op.drop_index('ix_analytics_product_daily_h3_index', table_name='analytics_product_daily')
    op.drop_index('ix_analytics_product_daily_product_id', table_name='analytics_product_daily')
    op.drop_index('ix_analytics_product_daily_sales_rep_id', table_name='analytics_product_daily')
    op.drop_table('analytics_product_daily')
    op.drop_index('ix_analytics_sales_rep_daily_date', table_name='analytics_sales_rep_daily')
    op.drop_index('ix_analytics_sales_rep_daily_sales_rep_id', table_name='analytics_sales_rep_daily')
    op.drop_table('analytics_sales_rep_daily')
    op.drop_index('idx_analytics_zone_product_daily_date_h3', table_name='analytics_zone_product_daily')
    op.drop_index('ix_analytics_zone_product_daily_date', table_name='analytics_zone_product_daily')
    op.drop_index('ix_analytics_zone_product_daily_h3_index', table_name='analytics_zone_product_daily')
    op.drop_index('ix_analytics_zone_product_daily_product_id', table_name='analytics_zone_product_daily')
    op.drop_table('analytics_zone_product_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_zone_product_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('h3_index', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_sales_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='analytics_zone_product_daily_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analytics_zone_product_daily_pkey'),
    sa.UniqueConstraint('date', 'h3_index', 'product_id', name='uq_analytics_zone_product_daily')
    )
    op.create_index('ix_analytics_zone_product_daily_product_id', 'analytics_zone_product_daily', ['product_id'], unique=False)
    op.create_index('ix_analytics_zone_product_daily_h3_index', 'analytics_zone_product_daily', ['h3_index'], unique=False)
    op.create_index('ix_analytics_zone_product_daily_date', 'analytics_zone_product_daily', ['date'], unique=False)
    op.create_index('idx_analytics_zone_product_daily_date_h3', 'analytics_zone_product_daily', ['date', 'h3_index'], unique=False)
    op.create_table('analytics_sales_rep_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sales_rep_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_orders', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_clients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_products_sold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sales_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], name='analytics_sales_rep_daily_sales_rep_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analytics_sales_rep_daily_pkey'),
    sa.UniqueConstraint('date', 'sales_rep_id', name='uq_analytics_sales_rep_daily')
    )
    op.create_index('ix_analytics_sales_rep_daily_sales_rep_id', 'analytics_sales_rep_daily', ['sales_rep_id'], unique=False)
    op.create_index('ix_analytics_sales_rep_daily_date', 'analytics_sales_rep_daily', ['date'], unique=False)
    op.create_table('analytics_product_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_rep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h3_index', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('quantity_sold', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('revenue_generated', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='analytics_product_daily_client_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='analytics_product_daily_product_id_fkey'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], name='analytics_product_daily_sales_rep_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analytics_product_daily_pkey'),
    sa.UniqueConstraint('date', 'product_id', 'quantity_sold', 'revenue_generated', name='uq_analytics_product_daily')
    )
    op.create_index('ix_analytics_product_daily_sales_rep_id', 'analytics_product_daily', ['sales_rep_id'], unique=False)
    op.create_index('ix_analytics_product_daily_product_id', 'analytics_product_daily', ['product_id'], unique=False)
    op.create_index('ix_analytics_product_daily_h3_index', 'analytics_product_daily', ['h3_index'], unique=False)
    op.create_index('ix_analytics_product_daily_date', 'analytics_product_daily', ['date'], unique=False)
    op.create_index('ix_analytics_product_daily_client_id', 'analytics_product_daily', ['client_id'], unique=False)
    op.create_index('idx_analytics_product_daily_date_product', 'analytics_product_daily', ['date', 'product_id'], unique=False)
    op.create_table('analytics_catalog_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sales_rep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zone_h3_index', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='analytics_catalog_events_product_id_fkey'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], name='analytics_catalog_events_sales_rep_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analytics_catalog_events_pkey')
    )
    op.create_index('ix_analytics_catalog_events_zone_h3_index', 'analytics_catalog_events', ['zone_h3_index'], unique=False)
    op.create_index('ix_analytics_catalog_events_visitor_id', 'analytics_catalog_events', ['visitor_id'], unique=False)
    op.create_index('ix_analytics_catalog_events_source', 'analytics_catalog_events', ['source'], unique=False)
    op.create_index('ix_analytics_catalog_events_session_id', 'analytics_catalog_events', ['session_id'], unique=False)
    op.create_index('ix_analytics_catalog_events_sales_rep_id', 'analytics_catalog_events', ['sales_rep_id'], unique=False)
    op.create_index('ix_analytics_catalog_events_product_id', 'analytics_catalog_events', ['product_id'], unique=False)
    op.create_index('ix_analytics_catalog_events_event_type', 'analytics_catalog_events', ['event_type'], unique=False)
    op.create_index('ix_analytics_catalog_events_created_at', 'analytics_catalog_events', ['created_at'], unique=False)
    op.create_index('idx_catalog_event_sales_rep_created', 'analytics_catalog_events', ['sales_rep_id', 'created_at'], unique=False)
    op.create_index('idx_catalog_event_product_created', 'analytics_catalog_events', ['product_id', 'created_at'], unique=False)
    op.create_index('idx_catalog_event_created_at', 'analytics_catalog_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
