"""fix online_customer_model

Revision ID: f90a99a4cc7f
Revises: 0ddd9f6fd678
Create Date: 2026-08-27 16:49:32.426619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90a99a4cc7f'
down_revision: Union[str, None] = '0ddd9f6fd678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
