"""fix analytics client daily

Revision ID: fb19054d04ad
Revises: 2cba3737ffc5
Create Date: 2026-06-16 21:22:18.599232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb19054d04ad'
down_revision: Union[str, None] = '2cba3737ffc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_client_daily', sa.Column('categories_summary', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_client_daily', 'categories_summary')
    # ### end Alembic commands ###
