"""remove product subcategory

Revision ID: fcf86696d73c
Revises: 258cd3868882
Create Date: 2026-03-20 13:29:36.531815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf86696d73c'
down_revision: Union[str, None] = '258cd3868882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_subcategory', table_name='products')
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_products_subcategory', 'products', ['subcategory'], unique=False)
    # ### end Alembic commands ###
